export const ROLES = Object.freeze({
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  TEAM_LEAD: "TEAM_LEAD",
  STAFF: "STAFF"
});

export const PERMISSIONS = Object.freeze({
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  MASTER_DATA_VIEW: "MASTER_DATA_VIEW",
  MASTER_DATA_MANAGE: "MASTER_DATA_MANAGE",
  TARGETS_VIEW: "TARGETS_VIEW",
  TARGETS_MANAGE: "TARGETS_MANAGE",
  ACTUALS_VIEW: "ACTUALS_VIEW",
  ACTUALS_MANAGE: "ACTUALS_MANAGE",
  IMPORTS_MANAGE: "IMPORTS_MANAGE",
  REPORTS_VIEW: "REPORTS_VIEW",
  REPORTS_EXPORT: "REPORTS_EXPORT",
  USERS_MANAGE: "USERS_MANAGE",
  AUDIT_LOGS_VIEW: "AUDIT_LOGS_VIEW"
});

const operationalPermissions = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.MASTER_DATA_VIEW,
  PERMISSIONS.TARGETS_VIEW,
  PERMISSIONS.TARGETS_MANAGE,
  PERMISSIONS.ACTUALS_VIEW,
  PERMISSIONS.ACTUALS_MANAGE,
  PERMISSIONS.IMPORTS_MANAGE,
  PERMISSIONS.REPORTS_VIEW,
  PERMISSIONS.REPORTS_EXPORT
];

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.MANAGER]: operationalPermissions,
  [ROLES.TEAM_LEAD]: operationalPermissions.filter((permission) => permission !== PERMISSIONS.MASTER_DATA_VIEW),
  [ROLES.STAFF]: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.REPORTS_VIEW]
});

export function permissionsForRole(role) {
  return ROLE_PERMISSIONS[role] ?? [];
}
